name: Test

on: push

jobs:
  format:
    name: Formatted correctly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - name: Install modules
        run: npm ci
      - name: Run formatting
        run: npm run format-check
  lint:
    name: No lint errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - name: Install modules
        run: npm ci
      - name: Run linting
        run: npm run lint
  test:
    name: Unit tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: dan-schel/node-db
  build:
    name: Builds successfully
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - name: Install modules
        run: npm ci
      - name: Run build
        run: npm run build
  bump:
    name: Bumps version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - name: Install modules
        run: npm ci
      - name: Confirm version bump
        run: npm run bump-check
